{"title": ["Apple Ipad Mini 4 128Gb Wi-Fi + Cellular (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-mini-4-128gb-wi-fi-cellular-gold/807085/"], "price": ["778"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/189921-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"url": ["https://www.jbhifi.com.au/computers-tablets/tablets/"], "project": ["comparison"], "spider": ["jbhifi"], "server": ["Michaels-MacBook-Pro.local"]}
{"title": ["Apple Ipad Mini 4 128Gb Wi-Fi + Cellular (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-mini-4-128gb-wi-fi-cellular-space-grey/807087/"], "price": ["778"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/189919-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Mini 4 128Gb Wi-Fi + Cellular (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-mini-4-128gb-wi-fi-cellular-silver/807086/"], "price": ["778"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/189923-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab S2 9.7\" Lte 64Gb (Black)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-s2-9-7-lte-64gb-black/956472/"], "price": ["849"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187490-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad 128Gb Wi-Fi + Cellular (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-128gb-wi-fi-cellular-gold/329962/"], "price": ["798"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/210468-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Mixx 510 12.2\" 2-In-1 Tablet (I5/128Gb)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/ingram-micro/lenovo-mixx-510-12-2-2-in-1-tablet-i5-128gb/313710/"], "price": ["799"], "spider": ["jbhifi"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad 128Gb Wi-Fi + Cellular (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-128gb-wi-fi-cellular-space-grey/329934/"], "price": ["798"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/210460-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Mixx 510 12.2\" 2-In-1 Tablet (I3)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/ingram-micro/lenovo-mixx-510-12-2-2-in-1-tablet-i3/313709/"], "price": ["699"], "spider": ["jbhifi"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Pro 4 Corem 128Gb Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-pro-4-corem-128gb-tablet/317884/"], "price": ["799"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/200847-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab S2 9.7\" Wifi 64Gb (White)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-s2-9-7-wifi-64gb-white/956469/"], "price": ["697"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187509-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab S2 8.0\" Lte 32Gb (Black)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-s2-8-0-lte-32gb-black/956468/"], "price": ["696"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187484-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Yoga Book 64Gb Android Tablet (Gun Metal)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/lenovo/lenovo-yoga-book-64gb-android-tablet-gun-metal/314265/"], "price": ["678"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/192554-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad 32Gb Wi-Fi + Cellular (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-32gb-wi-fi-cellular-space-grey/329926/"], "price": ["668"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/210456-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad 128Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-128gb-wi-fi-space-grey/329950/"], "price": ["598"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/210466-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab S2 9.7\" Wifi 64Gb (Black)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-s2-9-7-wifi-64gb-black/956471/"], "price": ["697"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187504-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad 128Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-128gb-wi-fi-gold/329970/"], "price": ["598"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/210463-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab A S Pen 10.1\" Lte 16Gb (Black)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-a-s-pen-10-1-lte-16gb-black/956466/"], "price": ["597"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187482-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Yoga Tab 3 Plus+ Lte Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/lenovo/lenovo-yoga-tab-3-plus-lte-tablet/324368/"], "price": ["579"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/198798-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Mini 4 128Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-mini-4-128gb-wi-fi-space-grey/807068/"], "price": ["578"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/189898-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Mini 4 128Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-mini-4-128gb-wi-fi-gold/807065/"], "price": ["578"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/189899-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Mini 4 128Gb Wi-Fi (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-mini-4-128gb-wi-fi-silver/807067/"], "price": ["578"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/189925-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab S2 8.0\" Wi-Fi 32Gb (Black)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-s2-8-0-wi-fi-32gb-black/956467/"], "price": ["548"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187487-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad 32Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-32gb-wi-fi-space-grey/329942/"], "price": ["468"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/210459-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad 32Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-32gb-wi-fi-gold/329966/"], "price": ["468"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/210464-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad 32Gb Wi-Fi (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-32gb-wi-fi-silver/329946/"], "price": ["468"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/210470-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab A 10.1\" Wi-Fi 16Gb (White)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-a-10-1-wi-fi-16gb-white/956465/"], "price": ["448"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187470-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab A 8.0 Lte 16Gb (White)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-a-8-0-lte-16gb-white/672182/"], "price": ["447"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/157276-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Yoga Tab 3 Plus+ 10\" Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/lenovo/lenovo-yoga-tab-3-plus-10-tablet/324367/"], "price": ["439"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/198795-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Miix 320 10\" Windows Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/lenovo/lenovo-miix-320-10-windows-tablet/421341/"], "price": ["399"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/214144-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Yoga Tab3 16Gb 10\" Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/lenovo/lenovo-yoga-tab3-16gb-10-tablet/956462/"], "price": ["298"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/183631-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 256Gb Wi-Fi + Cellular (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-256gb-wi-fi-cellular-gold/329984/"], "price": ["1548"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216920-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 256Gb Wi-Fi + Cellular (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-256gb-wi-fi-cellular-space-grey/329976/"], "price": ["1548"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216960-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 256Gb Wi-Fi + Cellular (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-256gb-wi-fi-cellular-silver/329980/"], "price": ["1548"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216940-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Pro I5 128Gb Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-pro-i5-128gb-tablet/452551/"], "price": ["1497"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215852-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 512Gb Wi-Fi (Rose Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-512gb-wi-fi-rose-gold/457537/"], "price": ["1428"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216891-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 512Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-512gb-wi-fi-gold/457559/"], "price": ["1428"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216869-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 512Gb Wi-Fi (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-512gb-wi-fi-silver/457554/"], "price": ["1428"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216877-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 512Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-512gb-wi-fi-space-grey/330006/"], "price": ["1428"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216853-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Book With Performance Base I7 1Tb (16Gb Ram)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-book-with-performance-base-i7-1tb-16gb-ram/326450/"], "price": ["4398"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/198278-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Pro I7 1Tb Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-pro-i7-1tb-tablet/452509/"], "price": ["3996"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215860-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Book With Performance Base I7 512Gb (16Gb Ram)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-book-with-performance-base-i7-512gb-16gb-ram/326449/"], "price": ["3738"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/198276-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Pro I7 512Gb Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-pro-i7-512gb-tablet/452557/"], "price": ["3298"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215868-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Book With Performance Base I7 256Gb (8Gb Ram)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-book-with-performance-base-i7-256gb-8gb-ram/326448/"], "price": ["3225"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/198277-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Hp Spectre X2 12-C009Tu 12\" I7 2-In-1 Detachable Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/hp/hp-spectre-x2-12-c009tu-12-i7-2-in-1-detachable-tablet/443470/"], "price": ["2798"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215803-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Pro I7 256Gb Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-pro-i7-256gb-tablet/452554/"], "price": ["2447"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215864-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Hp Spectre X2 12-C004Tu 12\" I5 2-In-1 Detachable Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/hp/hp-spectre-x2-12-c004tu-12-i5-2-in-1-detachable-tablet/443469/"], "price": ["2198"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215813-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Pro I5 256Gb Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-pro-i5-256gb-tablet/452553/"], "price": ["1998"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215859-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 512Gb Wi-Fi + Cellular (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-512gb-wi-fi-cellular-silver/457575/"], "price": ["1848"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216937-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 512Gb Wi-Fi + Cellular (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-512gb-wi-fi-cellular-gold/457579/"], "price": ["1848"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216917-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 512Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-512gb-wi-fi-gold/457566/"], "price": ["1648"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216926-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 512Gb Wi-Fi (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-512gb-wi-fi-silver/457562/"], "price": ["1648"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216946-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 512Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-512gb-wi-fi-space-grey/457558/"], "price": ["1648"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216968-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 512Gb Wi-Fi + Cellular (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-512gb-wi-fi-cellular-space-grey/457583/"], "price": ["1628"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216859-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 512Gb Wi-Fi + Cellular (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-512gb-wi-fi-cellular-gold/457591/"], "price": ["1628"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216867-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 512Gb Wi-Fi + Cellular (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-512gb-wi-fi-cellular-silver/457587/"], "price": ["1628"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216885-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 512Gb Wi-Fi + Cellular (Rose Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-512gb-wi-fi-cellular-rose-gold/457595/"], "price": ["1628"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216897-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 64Gb Wi-Fi + Cellular (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-64gb-wi-fi-cellular-silver/457634/"], "price": ["1398"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216935-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 64Gb Wi-Fi + Cellular (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-64gb-wi-fi-cellular-space-grey/457630/"], "price": ["1398"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216954-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 64Gb Wi-Fi + Cellular (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-64gb-wi-fi-cellular-gold/457638/"], "price": ["1398"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216914-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 256Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-256gb-wi-fi-space-grey/329964/"], "price": ["1348"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216973-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 256Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-256gb-wi-fi-gold/329972/"], "price": ["1348"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216929-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 256Gb Wi-Fi (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-256gb-wi-fi-silver/329968/"], "price": ["1348"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216951-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 256Gb Wi-Fi + Cellular (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-256gb-wi-fi-cellular-gold/457549/"], "price": ["1328"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216871-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 256Gb Wi-Fi + Cellular (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-256gb-wi-fi-cellular-space-grey/457541/"], "price": ["1328"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216857-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 256Gb Wi-Fi + Cellular (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-256gb-wi-fi-cellular-silver/457545/"], "price": ["1328"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216883-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 256Gb Wi-Fi + Cellular (Rose Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-256gb-wi-fi-cellular-rose-gold/457553/"], "price": ["1328"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216895-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Pro 4 I5 128Gb Tablet (Starter Pack)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-pro-4-i5-128gb-tablet-starter-pack/441412/"], "price": ["1297"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/214381-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 64Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-64gb-wi-fi-space-grey/457599/"], "price": ["1198"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216965-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 64Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-64gb-wi-fi-gold/457608/"], "price": ["1198"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216923-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 12.9-Inch 64Gb Wi-Fi (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-12-9-inch-64gb-wi-fi-silver/457604/"], "price": ["1198"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216943-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Microsoft Surface Pro Corem 128Gb Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/microsoft/microsoft-surface-pro-corem-128gb-tablet/452550/"], "price": ["1198"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215848-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 64Gb Wi-Fi + Cellular (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-64gb-wi-fi-cellular-space-grey/457538/"], "price": ["1178"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216861-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 64Gb Wi-Fi + Cellular (Rose Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-64gb-wi-fi-cellular-rose-gold/457550/"], "price": ["1178"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216899-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 64Gb Wi-Fi + Cellular (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-64gb-wi-fi-cellular-silver/457542/"], "price": ["1178"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216887-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 64Gb Wi-Fi + Cellular (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-64gb-wi-fi-cellular-gold/457546/"], "price": ["1178"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216873-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 256Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-256gb-wi-fi-space-grey/329989/"], "price": ["1128"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216851-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 256Gb Wi-Fi (Rose Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-256gb-wi-fi-rose-gold/330002/"], "price": ["1128"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216889-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 256Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-256gb-wi-fi-gold/329998/"], "price": ["1128"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216863-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 256Gb Wi-Fi (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-256gb-wi-fi-silver/329994/"], "price": ["1128"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216875-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 64Gb Wi-Fi (Rose Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-64gb-wi-fi-rose-gold/457625/"], "price": ["978"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216901-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 64Gb Wi-Fi (Space Grey)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-64gb-wi-fi-space-grey/457612/"], "price": ["978"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216855-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 64Gb Wi-Fi (Gold)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-64gb-wi-fi-gold/457621/"], "price": ["978"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216865-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Apple Ipad Pro 10.5-Inch 64Gb Wi-Fi (Silver)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/apple/apple-ipad-pro-10-5-inch-64gb-wi-fi-silver/457616/"], "price": ["978"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/216881-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Mixx 510 12.2\" 2-In-1 Tablet (I5/256Gb)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/ingram-micro/lenovo-mixx-510-12-2-2-in-1-tablet-i5-256gb/313711/"], "price": ["929"], "spider": ["jbhifi"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab A 8.0 Wifi 16Gb (White)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-a-8-0-wifi-16gb-white/672178/"], "price": ["294"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/157277-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Tab 3 10\" Businesstablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/lenovo/lenovo-tab-3-10-businesstablet/943564/"], "price": ["284"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/201181-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Yoga Tab3 16Gb 8\" Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/lenovo/lenovo-yoga-tab3-16gb-8-tablet/956461/"], "price": ["198"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/183636-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Samsung Galaxy Tab A 7.0\" Wi-Fi 8Gb (White)"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/samsung/samsung-galaxy-tab-a-7-0-wi-fi-8gb-white/956464/"], "price": ["197"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187477-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Lenovo Tab 3 A7-10 7\" Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/lenovo/lenovo-tab-3-a7-10-7-tablet/314282/"], "price": ["88"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/198788-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
{"title": ["Laser Mid786 7\" Android Tablet"], "url": ["https://www.jbhifi.com.au/computers-tablets/tablets/laser/laser-mid786-7-android-tablet/317347/"], "price": ["79"], "spider": ["jbhifi"], "image_urls": ["https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/201151-L-LO.jpg"], "server": ["Michaels-MacBook-Pro.local"], "project": ["comparison"]}
